SELECT
    DATE(PARSE_TIMESTAMP('%Y%m%d%H%M%S', CAST(DATE AS STRING))) as event_date,
    TIMESTAMP(PARSE_TIMESTAMP('%Y%m%d%H%M%S', CAST(DATE AS STRING))) as datetime,
    'BROAD_MARKET' as ticker,
    REGEXP_EXTRACT(DOCUMENTIDENTIFIER, r'https?://[^/]+/(.+)') as headline,
    DOCUMENTIDENTIFIER as url,
    REGEXP_REPLACE(
        REGEXP_REPLACE(
            REGEXP_EXTRACT(DOCUMENTIDENTIFIER, r'https?://([^/]+)'), 
            r'^www\.', ''
        ), 
        r'\.[^.]+$', ''
    ) as website_host
FROM
    `gdelt-bq.gdeltv2.gkg`
WHERE
    DATE(PARSE_TIMESTAMP('%Y%m%d%H%M%S', CAST(DATE AS STRING))) BETWEEN '2021-03-31' AND '2023-03-30'
    
    -- Reference keywords for financial/economic content
    AND (
        -- Central Banking & Monetary Policy
        UPPER(THEMES) LIKE '%FEDERAL_RESERVE%' OR UPPER(THEMES) LIKE '%FED%' OR UPPER(THEMES) LIKE '%ECB%' OR
        UPPER(THEMES) LIKE '%CENTRAL_BANK%' OR UPPER(THEMES) LIKE '%MONETARY_POLICY%' OR
        UPPER(THEMES) LIKE '%INTEREST_RATE%' OR UPPER(THEMES) LIKE '%RATE_HIKE%' OR UPPER(THEMES) LIKE '%RATE_CUT%' OR
        UPPER(THEMES) LIKE '%FOMC%' OR UPPER(THEMES) LIKE '%QUANTITATIVE_EASING%' OR UPPER(THEMES) LIKE '%TAPERING%' OR
        
        -- Bonds & Yields
        UPPER(THEMES) LIKE '%BOND_YIELD%' OR UPPER(THEMES) LIKE '%TREASURY%' OR UPPER(THEMES) LIKE '%YIELD_CURVE%' OR
        
        -- Inflation & Prices
        UPPER(THEMES) LIKE '%INFLATION%' OR UPPER(THEMES) LIKE '%DEFLATION%' OR UPPER(THEMES) LIKE '%CPI%' OR
        UPPER(THEMES) LIKE '%PCE%' OR UPPER(THEMES) LIKE '%CONSUMER_PRICES%' OR UPPER(THEMES) LIKE '%PRODUCER_PRICES%' OR
        
        -- Economic Growth
        UPPER(THEMES) LIKE '%ECONOMIC_GROWTH%' OR UPPER(THEMES) LIKE '%GDP%' OR UPPER(THEMES) LIKE '%RECESSION%' OR
        UPPER(THEMES) LIKE '%DOWNTURN%' OR UPPER(THEMES) LIKE '%CONTRACTION%' OR UPPER(THEMES) LIKE '%EXPANSION%' OR
        UPPER(THEMES) LIKE '%RECOVERY%' OR
        
        -- Manufacturing & PMI
        UPPER(THEMES) LIKE '%MANUFACTURING%' OR UPPER(THEMES) LIKE '%PMI%' OR UPPER(THEMES) LIKE '%ISM%' OR
        
        -- Consumer & Housing
        UPPER(THEMES) LIKE '%CONSUMER_SPENDING%' OR UPPER(THEMES) LIKE '%RETAIL_SALES%' OR UPPER(THEMES) LIKE '%HOUSING_MARKET%' OR
        
        -- Employment
        UPPER(THEMES) LIKE '%JOBS_REPORT%' OR UPPER(THEMES) LIKE '%EMPLOYMENT%' OR UPPER(THEMES) LIKE '%UNEMPLOYMENT%' OR
        UPPER(THEMES) LIKE '%NONFARM_PAYROLLS%' OR UPPER(THEMES) LIKE '%LABOR_MARKET%' OR UPPER(THEMES) LIKE '%WAGE_GROWTH%' OR
        
        -- Stock Market
        UPPER(THEMES) LIKE '%STOCK_MARKET%' OR UPPER(THEMES) LIKE '%MARKET_RALLY%' OR UPPER(THEMES) LIKE '%MARKET_CRASH%' OR
        UPPER(THEMES) LIKE '%MARKET_CORRECTION%' OR UPPER(THEMES) LIKE '%BULL_MARKET%' OR UPPER(THEMES) LIKE '%BEAR_MARKET%' OR
        
        -- Market Sentiment
        UPPER(THEMES) LIKE '%INVESTOR_SENTIMENT%' OR UPPER(THEMES) LIKE '%MARKET_CONFIDENCE%' OR UPPER(THEMES) LIKE '%VOLATILITY%' OR
        UPPER(THEMES) LIKE '%VIX%' OR UPPER(THEMES) LIKE '%FEAR_INDEX%' OR
        
        -- Market Psychology
        UPPER(THEMES) LIKE '%BUBBLE%' OR UPPER(THEMES) LIKE '%EUPHORIA%' OR UPPER(THEMES) LIKE '%PANIC%' OR
        UPPER(THEMES) LIKE '%FEAR%' OR UPPER(THEMES) LIKE '%GREED%' OR
        
        -- Market Indices
        UPPER(THEMES) LIKE '%S&P_500%' OR UPPER(THEMES) LIKE '%S%26P_500%' OR UPPER(THEMES) LIKE '%NASDAQ%' OR
        UPPER(THEMES) LIKE '%DOW_JONES%' OR UPPER(THEMES) LIKE '%RUSSELL_2000%' OR
        UPPER(THEMES) LIKE '%SPY%' OR UPPER(THEMES) LIKE '%QQQ%' OR UPPER(THEMES) LIKE '%DIA%' OR UPPER(THEMES) LIKE '%IWM%' OR
        
        -- Corporate
        UPPER(THEMES) LIKE '%EARNINGS_SEASON%' OR UPPER(THEMES) LIKE '%CORPORATE_PROFITS%' OR UPPER(THEMES) LIKE '%REVENUE_GROWTH%' OR
        UPPER(THEMES) LIKE '%PROFIT_OUTLOOK%' OR UPPER(THEMES) LIKE '%GUIDANCE%' OR
        
        -- Geopolitical & Policy
        UPPER(THEMES) LIKE '%GEOPOLITICAL%' OR UPPER(THEMES) LIKE '%TRADE_WAR%' OR UPPER(THEMES) LIKE '%TARIFFS%' OR
        UPPER(THEMES) LIKE '%SANCTIONS%' OR UPPER(THEMES) LIKE '%ELECTION%' OR UPPER(THEMES) LIKE '%GOVERNMENT_POLICY%' OR
        UPPER(THEMES) LIKE '%FISCAL_POLICY%' OR
        
        -- Crisis & Events
        UPPER(THEMES) LIKE '%CRISIS%' OR UPPER(THEMES) LIKE '%CONFLICT%' OR UPPER(THEMES) LIKE '%DISASTER%' OR
        
        -- URL-based keywords
        UPPER(DOCUMENTIDENTIFIER) LIKE '%FED%' OR UPPER(DOCUMENTIDENTIFIER) LIKE '%FEDERAL-RESERVE%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%INTEREST-RATE%' OR UPPER(DOCUMENTIDENTIFIER) LIKE '%INFLATION%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%GDP%' OR UPPER(DOCUMENTIDENTIFIER) LIKE '%RECESSION%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%EMPLOYMENT%' OR UPPER(DOCUMENTIDENTIFIER) LIKE '%MARKET%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%EARNINGS%' OR UPPER(DOCUMENTIDENTIFIER) LIKE '%ECONOMY%'
    )
    
    -- Exclude non-financial content
    AND NOT (
        UPPER(DOCUMENTIDENTIFIER) LIKE '%RECIPE%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%FOOD%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%COOKING%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%RESTAURANT%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%SPORTS%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%ENTERTAINMENT%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%CELEBRITY%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%LIFESTYLE%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%TRAVEL%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%WEATHER%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%FASHION%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%GAMING%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%MOVIE%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%MUSIC%' OR
        UPPER(THEMES) LIKE '%FOOD%' OR
        UPPER(THEMES) LIKE '%SPORTS%' OR
        UPPER(THEMES) LIKE '%ENTERTAINMENT%' OR
        UPPER(THEMES) LIKE '%WEATHER%' OR
        UPPER(THEMES) LIKE '%FASHION%'
    )
    
    AND DOCUMENTIDENTIFIER IS NOT NULL
    AND DOCUMENTIDENTIFIER LIKE 'http%'
    
    -- Financial news sources
    AND (
        UPPER(DOCUMENTIDENTIFIER) LIKE '%REUTERS.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%BLOOMBERG.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%CNBC.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%MARKETWATCH.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%FINANCE.YAHOO.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%WSJ.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%FORTUNE.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%FORBES.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%BUSINESSINSIDER.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%SEEKINGALPHA.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%FOOL.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%BARRONS.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%THESTREET.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%ECONOMIST.COM%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%FEDERALRESERVE.GOV%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%FED.GOV%' OR
        UPPER(DOCUMENTIDENTIFIER) LIKE '%TREASURY.GOV%'
    )
ORDER BY
    website_host ASC,
    datetime DESC